let listaDeDados =  [

    {
    id: 1,
    nomeComumDaPlanta: "Hibisco",
    nomeCientifico: "Hibiscus sabdariffa",
    imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Curcuma_longa_001.JPG/420px-Curcuma_longa_001.JPG",
    dadosMedicinais: "O hibisco é rico em antioxidantes e possui propriedades diuréticas, auxiliando no controle da pressão arterial e na redução do colesterol. Seu sabor levemente ácido é refrescante e agradável.",
    receita: "Adicione 1 colher de sopa de flores de hibisco secas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba frio ou quente.",
    contraIndicacoes: "Evite o consumo excessivo em caso de hipotensão. Consulte um médico em caso de gravidez ou lactação.",
    indicacao: ["Coração"],
    dicasMedicas: "O chá de hibisco pode ser um aliado na saúde cardiovascular, mas lembre-se de que o acompanhamento médico é fundamental para o controle da pressão arterial e do colesterol.",
    nome: "Sistema Cardiovascular",
    funcao: "Transporte de sangue, oxigênio e nutrientes.",
    componentes: ["Coração", "Vasos sanguíneos", "Sangue"]
    },
    {
    id: 2,
    nomeComumDaPlanta: "Espinheira-santa",
    nomeCientifico: "Maytenus ilicifolia",
    imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Maytenus_ilicifolia.jpg/420px-Maytenus_ilicifolia.jpg",
    dadosMedicinais: "A espinheira-santa possui propriedades antioxidantes e anti-inflamatórias, auxiliando na proteção do coração e na redução do colesterol. É tradicionalmente usada para tratar problemas digestivos e úlceras.",
    receita: "Adicione 1 colher de sopa de folhas de espinheira-santa picadas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
    contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
    indicacao: ["Coração", "Estômago"],
    dicasMedicas: "A espinheira-santa pode ser benéfica para o sistema cardiovascular e digestivo, mas o acompanhamento médico é essencial para o tratamento de qualquer condição.",
    nome: "Sistema Cardiovascular",
    funcao: "Transporte de sangue, oxigênio e nutrientes.",
    componentes: ["Coração", "Vasos sanguíneos", "Sangue"]
    },
    {
    id: 3,
    nomeComumDaPlanta: "Alho",
    nomeCientifico: "Allium sativum",
    imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Garlic.jpg/420px-Garlic.jpg",
    dadosMedicinais: "O alho é conhecido por suas propriedades cardioprotetoras, ajudando a reduzir o colesterol, a pressão arterial e a prevenir a formação de coágulos sanguíneos. Também possui ação antimicrobiana e antioxidante.",
    receita: "Amasse 2 dentes de alho e adicione em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 1 vez ao dia.",
    contraIndicacoes: "Evite o consumo excessivo em caso de problemas de coagulação sanguínea ou antes de cirurgias. Consulte um médico em caso de gravidez ou lactação.",
    indicacao: ["Coração", "Sangue"],
    dicasMedicas: "O alho pode ser um aliado na saúde cardiovascular, mas não substitui o acompanhamento médico e o tratamento adequado.",
    nome: "Sistema Cardiovascular",
    funcao: "Transporte de sangue, oxigênio e nutrientes.",
    componentes: ["Coração", "Vasos sanguíneos", "Sangue"]
    },
    {
    id: 4,
    nomeComumDaPlanta: "Gengibre",
    nomeCientifico: "Zingiber officinale",
    imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Zingiber_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-146.jpg/420px-Zingiber_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-146.jpg",
    dadosMedicinais: "O gengibre possui propriedades anti-inflamatórias e antioxidantes, auxiliando na redução do colesterol e na prevenção de doenças cardiovasculares. Também melhora a circulação sanguínea e possui ação digestiva.",
    receita: "Rale 1 pedaço de gengibre e adicione em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 2 vezes ao dia.",
    contraIndicacoes: "Evite o consumo excessivo em caso de problemas de coagulação sanguínea ou úlceras estomacais. Consulte um médico em caso de gravidez ou lactação.",
    indicacao: ["Coração", "Sangue", "Estômago"],
    dicasMedicas: "O gengibre pode ser um aliado na saúde cardiovascular e digestiva, mas lembre-se de buscar orientação médica para um tratamento completo.",
    nome: "Sistema Cardiovascular",
    funcao: "Transporte de sangue, oxigênio e nutrientes.",
    componentes: ["Coração", "Vasos sanguíneos", "Sangue"]
    },
    {
    id: 5,
    nomeComumDaPlanta: "Cavalinha",
    nomeCientifico: "Equisetum arvense",
    imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Equisetum_arvense_foliage.jpg/420px-Equisetum_arvense_foliage.jpg",
    dadosMedicinais: "A cavalinha é rica em minerais, como silício, que auxilia na saúde dos vasos sanguíneos e na prevenção da arteriosclerose. Também possui ação diurética e anti-inflamatória.",
    receita: "Adicione 1 colher de sopa de cavalinha seca em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
    contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou problemas renais. Consulte um médico antes de usar.",
    indicacao: ["Coração", "Vasos sanguíneos"],
    dicasMedicas: "A cavalinha pode auxiliar na saúde cardiovascular, mas é fundamental o acompanhamento médico para o tratamento de qualquer condição.",
    nome: "Sistema Cardiovascular",
    funcao: "Transporte de sangue, oxigênio e nutrientes.",
    componentes: ["Coração", "Vasos sanguíneos", "Sangue"]
    },
    {
    id: 6,
    nomeComumDaPlanta: "Melissa",
    nomeCientifico: "Melissa officinalis",
    imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Lemon_balm_plant.jpg/330px-Lemon_balm_plant.jpg",
    dadosMedicinais: "A melissa possui propriedades calmantes e relaxantes, auxiliando no controle da pressão arterial e na redução do estresse, fatores que podem influenciar a saúde cardiovascular. Também melhora a digestão e promove o bem-estar.",
    receita: "Adicione 1 colher de sopa de folhas de melissa frescas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 2 vezes ao dia.",
    contraIndicacoes: "Evite o consumo excessivo em caso de hipotireoidismo. Consulte um médico em caso de gravidez ou lactação.",
    indicacao: ["Coração", "Estômago", "Cérebro"],
    dicasMedicas: "A melissa pode ser uma aliada na saúde cardiovascular, mas não substitui o acompanhamento médico e o tratamento adequado.",
    nome: "Sistema Cardiovascular",
    funcao: "Transporte de sangue, oxigênio e nutrientes.",
    componentes: ["Coração", "Vasos sanguíneos", "Sangue"]
    },
    {
        id: 7,
        nomeComumDaPlanta: "Tomilho",
        nomeCientifico: "Thymus vulgaris",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flowering_thyme.JPG/420px-Flowering_thyme.JPG",
        dadosMedicinais: "O tomilho possui propriedades expectorantes e antissépticas, auxiliando na expectoração do muco e no combate a infecções respiratórias. Seu aroma também promove a sensação de bem-estar.",
        receita: "Adicione 1 colher de sopa de folhas de tomilho frescas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de hipertireoidismo ou sensibilidade à planta. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Pulmões", "Brônquios"],
        dicasMedicas: "O chá de tomilho pode auxiliar no alívio dos sintomas respiratórios, mas é importante buscar orientação médica para o diagnóstico e tratamento adequados.",
        nome: "Sistema Respiratório",
        funcao: "Troca de gases (oxigênio e dióxido de carbono).",
        componentes: ["Pulmões", "Traqueia", "Brônquios", "Diafragma"]
      },
      {
        id: 8,
        nomeComumDaPlanta: "Poejo",
        nomeCientifico: "Mentha pulegium",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mentha_pulegium_kz.jpg/330px-Mentha_pulegium_kz.jpg",
        dadosMedicinais: "O poejo possui ação expectorante e broncodilatadora, auxiliando na eliminação do muco e na abertura dos brônquios. É tradicionalmente usado para tratar gripes, resfriados e bronquites.",
        receita: "Adicione 1 colher de sopa de folhas de poejo frescas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou problemas hepáticos. Consulte um médico antes de usar.",
        indicacao: ["Pulmões", "Brônquios"],
        dicasMedicas: "O chá de poejo pode ser um aliado no tratamento de problemas respiratórios, mas lembre-se de buscar orientação médica para um tratamento completo.",
        nome: "Sistema Respiratório",
        funcao: "Troca de gases (oxigênio e dióxido de carbono).",
        componentes: ["Pulmões", "Traqueia", "Brônquios", "Diafragma"]
      },
      {
        id: 9,
        nomeComumDaPlanta: "Malva",
        nomeCientifico: "Malva sylvestris",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gardenology.org-IMG_2751_rbgs11jan.jpg/330px-Gardenology.org-IMG_2751_rbgs11jan.jpg",
        dadosMedicinais: "A malva possui propriedades anti-inflamatórias e calmantes, auxiliando no alívio da tosse, irritação na garganta e inflamações respiratórias. Também possui ação emoliente, suavizando as mucosas.",
        receita: "Adicione 1 colher de sopa de flores de malva secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez ou lactação. Consulte um médico antes de usar.",
        indicacao: ["Pulmões", "Traqueia", "Garganta"],
        dicasMedicas: "O chá de malva pode ser um aliado no cuidado da saúde respiratória, mas é importante procurar um médico em caso de sintomas persistentes.",
        nome: "Sistema Respiratório",
        funcao: "Troca de gases (oxigênio e dióxido de carbono).",
        componentes: ["Pulmões", "Traqueia", "Brônquios", "Diafragma"]
      },
      {
        id: 10,
        nomeComumDaPlanta: "Sálvia",
        nomeCientifico: "Salvia officinalis",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Salvia_officinalis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-126.jpg/420px-Salvia_officinalis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-126.jpg",
        dadosMedicinais: "A sálvia possui propriedades anti-inflamatórias, antissépticas e expectorantes, auxiliando no tratamento de gripes, resfriados, tosse e dor de garganta. Também possui ação antioxidante.",
        receita: "Adicione 1 colher de sopa de folhas de sálvia frescas em 1 xícara de água fervente. Abafe por 5 minutos, coe e faça gargarejos ou beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de epilepsia ou sensibilidade à planta. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Pulmões", "Traqueia", "Garganta"],
        dicasMedicas: "A sálvia pode ser uma aliada no cuidado da saúde respiratória, mas não substitui o acompanhamento médico em caso de problemas respiratórios persistentes.",
        nome: "Sistema Respiratório",
        funcao: "Troca de gases (oxigênio e dióxido de carbono).",
        componentes: ["Pulmões", "Traqueia", "Brônquios", "Diafragma"]
      },
      {
        id: 11,
        nomeComumDaPlanta: "Boldo-do-chile",
        nomeCientifico: "Peumus boldus",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Peumus_boldus_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-104.jpg",
        dadosMedicinais: "O boldo-do-chile é conhecido por suas propriedades digestivas e hepatoprotetoras, auxiliando na digestão de gorduras, no funcionamento do fígado e na produção de bile. Também possui ação antioxidante e anti-inflamatória.",
        receita: "Adicione 1 colher de sopa de folhas de boldo-do-chile picadas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba após as refeições.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, obstrução das vias biliares ou problemas hepáticos graves. Consulte um médico antes de usar.",
        indicacao: ["Fígado", "Estômago", "Intestinos"],
        dicasMedicas: "O boldo-do-chile pode ser um aliado na saúde digestiva, mas o acompanhamento médico é essencial para o tratamento de qualquer condição.",
        nome: "Sistema Digestivo",
        funcao: "Quebra dos alimentos e absorção de nutrientes.",
        componentes: ["Boca", "Esôfago", "Estômago", "Intestinos", "Fígado", "Pâncreas"]
      },
      {
        id: 12,
        nomeComumDaPlanta: "Carqueja",
        nomeCientifico: "Baccharis trimera",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Carqueja2.jpg/420px-Carqueja2.jpg",
        dadosMedicinais: "A carqueja possui propriedades digestivas, diuréticas e hepatoprotetoras, auxiliando na digestão, no funcionamento do fígado e na eliminação de toxinas. Também possui ação antioxidante e anti-inflamatória.",
        receita: "Adicione 1 colher de sopa de folhas de carqueja picadas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Fígado", "Estômago", "Intestinos"],
        dicasMedicas: "A carqueja pode ser benéfica para a saúde digestiva, mas o acompanhamento médico é fundamental para o tratamento de qualquer condição.",
        nome: "Sistema Digestivo",
        funcao: "Quebra dos alimentos e absorção de nutrientes.",
        componentes: ["Boca", "Esôfago", "Estômago", "Intestinos", "Fígado", "Pâncreas"]
      },
      {
        id: 13,
        nomeComumDaPlanta: "Funcho",
        nomeCientifico: "Foeniculum vulgare",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Foeniculum_vulgare.JPG/420px-Foeniculum_vulgare.JPG",
        dadosMedicinais: "O funcho possui propriedades digestivas, auxiliando no alívio de gases, cólicas e indigestão. Também estimula a produção de enzimas digestivas e possui ação anti-inflamatória.",
        receita: "Adicione 1 colher de chá de sementes de funcho em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba após as refeições.",
        contraIndicacoes: "Evite o consumo excessivo em caso de gravidez ou lactação. Consulte um médico antes de usar.",
        indicacao: ["Estômago", "Intestinos"],
        dicasMedicas: "O funcho pode ajudar a melhorar a digestão, mas não substitui o acompanhamento médico em caso de problemas digestivos persistentes.",
        nome: "Sistema Digestivo",
        funcao: "Quebra dos alimentos e absorção de nutrientes.",
        componentes: ["Boca", "Esôfago", "Estômago", "Intestinos", "Fígado", "Pâncreas"]
      },
      {
        id: 14,
        nomeComumDaPlanta: "Alcachofra",
        nomeCientifico: "Cynara scolymus",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Artichautfleur.jpg/420px-Artichautfleur.jpg",
        dadosMedicinais: "A alcachofra possui propriedades digestivas e hepatoprotetoras, auxiliando na digestão de gorduras, no funcionamento do fígado e na produção de bile. Também possui ação antioxidante e diurética.",
        receita: "Ferva 1 litro de água e adicione 2 folhas de alcachofra picadas. Abafe por 10 minutos, coe e beba ao longo do dia.",
        contraIndicacoes: "Evite o uso em caso de obstrução das vias biliares ou hipersensibilidade à planta. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Fígado", "Estômago", "Intestinos"],
        dicasMedicas: "A alcachofra pode ser uma aliada na saúde digestiva, mas é importante procurar um médico em caso de sintomas persistentes.",
        nome: "Sistema Digestivo",
        funcao: "Quebra dos alimentos e absorção de nutrientes.",
        componentes: ["Boca", "Esôfago", "Estômago", "Intestinos", "Fígado", "Pâncreas"]
      },
      {
        id: 15,
        nomeComumDaPlanta: "Valeriana",
        nomeCientifico: "Valeriana officinalis",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Valeriana_officinalis_-_Niitv%C3%A4lja.jpg/420px-Valeriana_officinalis_-_Niitv%C3%A4lja.jpg",
        dadosMedicinais: "A valeriana é conhecida por suas propriedades calmantes e sedativas, auxiliando no combate à ansiedade, insônia e agitação nervosa. Seu aroma promove o relaxamento e melhora a qualidade do sono.",
        receita: "Adicione 1 colher de sopa de raiz de valeriana picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba antes de dormir.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Cérebro"],
        dicasMedicas: "A valeriana pode ser uma aliada no combate à insônia e ansiedade, mas é importante buscar ajuda profissional em caso de transtornos persistentes.",
        nome: "Sistema Nervoso",
        funcao: "Controle e coordenação de todas as funções do corpo.",
        componentes: ["Cérebro", "Medula espinhal", "Nervos"]
      },
      {
        id: 16,
        nomeComumDaPlanta: "Passiflora",
        nomeCientifico: "Passiflora incarnata",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/OQ_Passion_flower.jpg/420px-OQ_Passion_flower.jpg",
        dadosMedicinais: "A passiflora possui propriedades calmantes e ansiolíticas, auxiliando no combate à ansiedade, estresse e insônia. Também pode ajudar a aliviar dores de cabeça e tensões musculares.",
        receita: "Adicione 1 colher de sopa de folhas de passiflora secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba antes de dormir.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Cérebro"],
        dicasMedicas: "A passiflora pode ser um aliado no relaxamento e no combate à ansiedade, mas é fundamental procurar um médico em caso de transtornos persistentes.",
        nome: "Sistema Nervoso",
        funcao: "Controle e coordenação de todas as funções do corpo.",
        componentes: ["Cérebro", "Medula espinhal", "Nervos"]
      },
      {
        id: 17,
        nomeComumDaPlanta: "Mulungu",
        nomeCientifico: "Erythrina mulungu",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Erythrina_mulungu.jpg/330px-Erythrina_mulungu.jpg",
        dadosMedicinais: "O mulungu possui propriedades calmantes e sedativas, auxiliando no combate à ansiedade, insônia e agitação nervosa. Também pode ajudar a aliviar dores musculares e promover o relaxamento.",
        receita: "Adicione 1 colher de sopa de casca de mulungu picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba antes de dormir.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Cérebro"],
        dicasMedicas: "O mulungu pode ser um aliado no relaxamento e no combate à insônia, mas é importante buscar ajuda profissional em caso de transtornos de ansiedade ou sono persistentes.",
        nome: "Sistema Nervoso",
        funcao: "Controle e coordenação de todas as funções do corpo.",
        componentes: ["Cérebro", "Medula espinhal", "Nervos"]
      },
      {
        id: 18,
        nomeComumDaPlanta: "Ginkgo biloba",
        nomeCientifico: "Ginkgo biloba",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/GINKGOBAUM-2.jpg/330px-GINKGOBAUM-2.jpg",
        dadosMedicinais: "O ginkgo biloba melhora a circulação sanguínea cerebral, auxiliando na memória, concentração e funções cognitivas. Também possui ação antioxidante e neuroprotetora.",
        receita: "Adicione 1 colher de chá de folhas de ginkgo biloba secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, problemas de coagulação sanguínea ou antes de cirurgias. Consulte um médico antes de usar.",
        indicacao: ["Cérebro"],
        dicasMedicas: "O ginkgo biloba pode ser um aliado na saúde cerebral, mas lembre-se de que o acompanhamento médico é fundamental para o tratamento de qualquer condição.",
        nome: "Sistema Nervoso",
        funcao: "Controle e coordenação de todas as funções do corpo.",
        componentes: ["Cérebro", "Medula espinhal", "Nervos"]
      },
      {
        id: 19,
        nomeComumDaPlanta: "Alecrim",
        nomeCientifico: "Rosmarinus officinalis",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Rosemary_bush.jpg/420px-Rosemary_bush.jpg",
        dadosMedicinais: "O alecrim possui propriedades estimulantes e antioxidantes, auxiliando na melhora da memória, concentração e funções cognitivas. Também pode ajudar a aliviar dores de cabeça e fadiga mental.",
        receita: "Adicione 1 colher de sopa de folhas de alecrim frescas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de hipertensão ou sensibilidade à planta. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Cérebro"],
        dicasMedicas: "O alecrim pode ser um aliado na saúde cerebral, mas não substitui o acompanhamento médico e o tratamento adequado.",
        nome: "Sistema Nervoso",
        funcao: "Controle e coordenação de todas as funções do corpo.",
        componentes: ["Cérebro", "Medula espinhal", "Nervos"]
      },
      {
        id: 20,
        nomeComumDaPlanta: "Tília",
        nomeCientifico: "Tilia cordata",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Tilia-cordata2.JPG/420px-Tilia-cordata2.JPG",
        dadosMedicinais: "A tília possui propriedades calmantes e relaxantes, auxiliando no combate à ansiedade, estresse e insônia. Seu aroma suave promove a sensação de tranquilidade e bem-estar.",
        receita: "Adicione 1 colher de sopa de flores de tília secas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba antes de dormir.",
        contraIndicacoes: "Evite o consumo excessivo em caso de problemas cardíacos. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Cérebro"],
        dicasMedicas: "A tília pode ser uma aliada no relaxamento e no combate à insônia, mas é fundamental procurar um médico em caso de transtornos de ansiedade ou sono persistentes.",
        nome: "Sistema Nervoso",
        funcao: "Controle e coordenação de todas as funções do corpo.",
        componentes: ["Cérebro", "Medula espinhal", "Nervos"]
      },
      {
        id: 21,
        nomeComumDaPlanta: "Cavalinha",
        nomeCientifico: "Equisetum arvense",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Equisetum_arvense_foliage.jpg/420px-Equisetum_arvense_foliage.jpg",
        dadosMedicinais: "A cavalinha é rica em minerais, incluindo iodo, que é essencial para a produção de hormônios da tireoide. Também possui ação diurética e remineralizante.",
        receita: "Adicione 1 colher de sopa de cavalinha seca em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou problemas renais. Consulte um médico antes de usar.",
        indicacao: ["Tireoide"],
        dicasMedicas: "A cavalinha pode auxiliar na saúde da tireoide, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados.",
        nome: "Sistema Endócrino",
        funcao: "Produção de hormônios reguladores.",
        componentes: ["Tireoide", "Hipófise", "Pâncreas", "Glândulas suprarrenais"]
      },
      {
        id: 22,
        nomeComumDaPlanta: "Ginseng",
        nomeCientifico: "Panax ginseng",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Ginsengpflanze.jpg/420px-Ginsengpflanze.jpg",
        dadosMedicinais: "O ginseng é conhecido por suas propriedades adaptogênicas, auxiliando o corpo a lidar com o estresse e equilibrando o sistema hormonal. Também pode melhorar a energia e a vitalidade.",
        receita: "Adicione 1 colher de chá de raiz de ginseng em pó em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 1 vez ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, hipertensão ou problemas cardíacos. Consulte um médico antes de usar.",
        indicacao: ["Glândulas suprarrenais"],
        dicasMedicas: "O ginseng pode ser um aliado no combate ao estresse e no equilíbrio hormonal, mas é importante buscar orientação médica para um tratamento completo.",
        nome: "Sistema Endócrino",
        funcao: "Produção de hormônios reguladores.",
        componentes: ["Tireoide", "Hipófise", "Pâncreas", "Glândulas suprarrenais"]
      },
      {
        id: 23,
        nomeComumDaPlanta: "Amora",
        nomeCientifico: "Morus nigra",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Amora_fruto.jpg/375px-Amora_fruto.jpg",
        dadosMedicinais: "As folhas de amora possuem compostos que podem auxiliar na regulação dos níveis de açúcar no sangue, sendo tradicionalmente utilizadas para auxiliar no controle do diabetes. Também possuem ação antioxidante.",
        receita: "Adicione 1 colher de sopa de folhas de amora secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de hipoglicemia. Consulte um médico antes de usar, especialmente se estiver tomando medicamentos para diabetes.",
        indicacao: ["Pâncreas"],
        dicasMedicas: "O chá de folhas de amora pode ser um complemento no controle do diabetes, mas o acompanhamento médico e o tratamento adequado são fundamentais.",
        nome: "Sistema Endócrino",
        funcao: "Produção de hormônios reguladores.",
        componentes: ["Tireoide", "Hipófise", "Pâncreas", "Glândulas suprarrenais"]
      },
      {
        id: 24,
        nomeComumDaPlanta: "Alfavaca",
        nomeCientifico: "Ocimum basilicum",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/2008_03_15_-_Ocimum_basilicum_5.JPG/420px-2008_03_15_-_Ocimum_basilicum_5.JPG",
        dadosMedicinais: "A alfavaca possui propriedades adaptogênicas, auxiliando o corpo a lidar com o estresse e regulando a produção de cortisol, o hormônio do estresse. Também possui ação antioxidante e anti-inflamatória.",
        receita: "Adicione 1 colher de sopa de folhas de alfavaca frescas em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de gravidez ou lactação. Consulte um médico antes de usar.",
        indicacao: ["Glândulas suprarrenais"],
        dicasMedicas: "A alfavaca pode ser uma aliada no combate ao estresse, mas é importante buscar ajuda profissional em caso de transtornos de ansiedade ou estresse persistentes.",
        nome: "Sistema Endócrino",
        funcao: "Produção de hormônios reguladores.",
        componentes: ["Tireoide", "Hipófise", "Pâncreas", "Glândulas suprarrenais"]
      },
      {
        id: 25,
        nomeComumDaPlanta: "Ashwagandha",
        nomeCientifico: "Withania somnifera",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/WithaniaFruit.jpg/420px-WithaniaFruit.jpg",
        dadosMedicinais: "A ashwagandha é uma planta adaptogênica que auxilia o corpo a lidar com o estresse e promove o equilíbrio hormonal. Também pode melhorar a energia, a função cognitiva e a qualidade do sono.",
        receita: "Adicione 1 colher de chá de raiz de ashwagandha em pó em 1 xícara de leite quente ou água. Misture bem e beba 1 vez ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, hipotireoidismo ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Tireoide", "Glândulas suprarrenais"],
        dicasMedicas: "A ashwagandha pode ser benéfica para o sistema endócrino, mas o acompanhamento médico é essencial para o tratamento de qualquer condição hormonal.",
        nome: "Sistema Endócrino",
        funcao: "Produção de hormônios reguladores.",
        componentes: ["Tireoide", "Hipófise", "Pâncreas", "Glândulas suprarrenais"]
      },
      {
        id: 26,
        nomeComumDaPlanta: "Cavalinha",
        nomeCientifico: "Equisetum arvense",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Equisetum_arvense_foliage.jpg/420px-Equisetum_arvense_foliage.jpg",
        dadosMedicinais: "A cavalinha é conhecida por suas propriedades diuréticas, auxiliando na eliminação de líquidos e toxinas do organismo. Rica em minerais, também contribui para a saúde dos rins e do trato urinário.",
        receita: "Adicione 1 colher de sopa de cavalinha seca em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou problemas renais. Consulte um médico antes de usar.",
        indicacao: ["Rins", "Bexiga"],
        dicasMedicas: "A cavalinha pode auxiliar na saúde do sistema excretor, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema.",
        nome: "Sistema Excretor",
        funcao: "Eliminação de resíduos metabólicos.",
        componentes: ["Rins", "Ureteres", "Bexiga", "Uretra"]
      },
      {
        id: 27,
        nomeComumDaPlanta: "Quebra-pedra",
        nomeCientifico: "Phyllanthus niruri",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Quebra-Pedra._Phyllanthus_niruri.JPG/420px-Quebra-Pedra._Phyllanthus_niruri.JPG",
        dadosMedicinais: "A quebra-pedra é tradicionalmente usada para auxiliar na eliminação de cálculos renais e na prevenção de infecções urinárias. Possui propriedades diuréticas e anti-inflamatórias.",
        receita: "Adicione 1 colher de sopa de quebra-pedra seca em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Rins", "Ureteres"],
        dicasMedicas: "A quebra-pedra pode ser um auxiliar na saúde renal, mas o acompanhamento médico é essencial para o tratamento de cálculos renais ou qualquer problema do sistema excretor.",
        nome: "Sistema Excretor",
        funcao: "Eliminação de resíduos metabólicos.",
        componentes: ["Rins", "Ureteres", "Bexiga", "Uretra"]
      },
      {
        id: 28,
        nomeComumDaPlanta: "Dente-de-leão",
        nomeCientifico: "Taraxacum officinale",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Taraxacum_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-135.jpg/330px-Taraxacum_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-135.jpg",
        dadosMedicinais: "O dente-de-leão possui propriedades diuréticas e depurativas, auxiliando na eliminação de toxinas e no bom funcionamento dos rins. Também pode ajudar a aliviar a retenção de líquidos.",
        receita: "Adicione 1 colher de sopa de folhas de dente-de-leão picadas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de obstrução das vias biliares ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Rins", "Fígado"],
        dicasMedicas: "O dente-de-leão pode ser um aliado na saúde do sistema excretor e do fígado, mas o acompanhamento médico é fundamental para o tratamento de qualquer condição.",
        nome: "Sistema Excretor",
        funcao: "Eliminação de resíduos metabólicos.",
        componentes: ["Rins", "Ureteres", "Bexiga", "Uretra"]
      },
      {
        id: 29,
        nomeComumDaPlanta: "Bardana",
        nomeCientifico: "Arctium lappa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/ArctiumLappa1.jpg/420px-ArctiumLappa1.jpg",
        dadosMedicinais: "A bardana possui propriedades diuréticas e depurativas, auxiliando na eliminação de toxinas e no bom funcionamento dos rins e da pele. Também pode ajudar a aliviar problemas de pele, como acne e eczema.",
        receita: "Adicione 1 colher de sopa de raiz de bardana picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez ou lactação. Consulte um médico antes de usar.",
        indicacao: ["Rins", "Pele"],
        dicasMedicas: "A bardana pode auxiliar na saúde do sistema excretor e da pele, mas o acompanhamento médico é fundamental para o tratamento de qualquer condição.",
        nome: "Sistema Excretor",
        funcao: "Eliminação de resíduos metabólicos.",
        componentes: ["Rins", "Ureteres", "Bexiga", "Uretra"]
      },
      {
        id: 30,
        nomeComumDaPlanta: "Uva-ursina",
        nomeCientifico: "Arctostaphylos uva-ursi",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Arctostaphylos_uva-ursi_25924.JPG/450px-Arctostaphylos_uva-ursi_25924.JPG",
        dadosMedicinais: "A uva-ursina possui propriedades antissépticas e adstringentes, sendo tradicionalmente usada para auxiliar no tratamento de infecções urinárias e inflamações da bexiga. ",
        receita: "Adicione 1 colher de sopa de folhas de uva-ursina secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, problemas renais ou úlceras estomacais. Consulte um médico antes de usar.",
        indicacao: ["Rins", "Bexiga", "Uretra"],
        dicasMedicas: "A uva-ursina pode ser um auxiliar no tratamento de infecções urinárias, mas o acompanhamento médico é essencial para o diagnóstico e tratamento adequados.",
        nome: "Sistema Excretor",
        funcao: "Eliminação de resíduos metabólicos.",
        componentes: ["Rins", "Ureteres", "Bexiga", "Uretra"]
      },
      {
        id: 31,
        nomeComumDaPlanta: "Equinácea",
        nomeCientifico: "Echinacea purpurea",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/EchinaceaPurpureaMaxima1a.UME.JPG/375px-EchinaceaPurpureaMaxima1a.UME.JPG",
        dadosMedicinais: "A equinácea é conhecida por suas propriedades estimulantes do sistema imunológico, auxiliando na prevenção e no combate a gripes, resfriados e outras infecções. Possui ação anti-inflamatória e antioxidante.",
        receita: "Adicione 1 colher de sopa de raiz de equinácea picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de doenças autoimunes ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Sistema Imunológico"],
        dicasMedicas: "A equinácea pode fortalecer o sistema imunológico, mas o acompanhamento médico é essencial para a prevenção e o tratamento de doenças.",
        nome: "Sistema Imunológico",
        funcao: "Proteção contra doenças e infecções.",
        componentes: ["Glóbulos brancos", "Linfócitos", "Macrófagos", "Timo", "Baço"]
      },
      {
        id: 32,
        nomeComumDaPlanta: "Própolis",
        nomeCientifico: "Própolis",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Propolis_in_beehives.jpg/330px-Propolis_in_beehives.jpg",
        dadosMedicinais: "A própolis é uma substância resinosa produzida pelas abelhas, rica em compostos bioativos com propriedades antimicrobianas, anti-inflamatórias e antioxidantes. Auxilia no fortalecimento do sistema imunológico e na prevenção de infecções.",
        receita: "Adicione 20 gotas de extrato de própolis em 1 xícara de água morna ou suco de sua preferência. Beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de alergia a produtos apícolas. Consulte um médico antes de usar.",
        indicacao: ["Sistema Imunológico"],
        dicasMedicas: "A própolis pode ser um aliado na saúde do sistema imunológico, mas não substitui o acompanhamento médico e o tratamento adequado.",
        nome: "Sistema Imunológico",
        funcao: "Proteção contra doenças e infecções.",
        componentes: ["Glóbulos brancos", "Linfócitos", "Macrófagos", "Timo", "Baço"]
      },
      {
        id: 33,
        nomeComumDaPlanta: "Astragalus",
        nomeCientifico: "Astragalus membranaceus",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Borrego_Milkvetch_up_close.jpg/330px-Borrego_Milkvetch_up_close.jpg",
        dadosMedicinais: "O astragalus é uma planta adaptogênica que auxilia o corpo a lidar com o estresse e fortalece o sistema imunológico. Possui ação antioxidante e anti-inflamatória.",
        receita: "Adicione 1 colher de chá de raiz de astragalus em pó em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de doenças autoimunes ou durante o uso de medicamentos imunossupressores. Consulte um médico antes de usar.",
        indicacao: ["Sistema Imunológico"],
        dicasMedicas: "O astragalus pode ser um aliado na saúde do sistema imunológico, mas o acompanhamento médico é essencial para a prevenção e o tratamento de doenças.",
        nome: "Sistema Imunológico",
        funcao: "Proteção contra doenças e infecções.",
        componentes: ["Glóbulos brancos", "Linfócitos", "Macrófagos", "Timo", "Baço"]
      },
      {
        id: 34,
        nomeComumDaPlanta: "Unha de gato",
        nomeCientifico: "Uncaria tomentosa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Uncaria_tomentosa.png/420px-Uncaria_tomentosa.png",
        dadosMedicinais: "A unha de gato é conhecida por suas propriedades estimulantes do sistema imunológico e anti-inflamatórias. Auxilia no combate a infecções e inflamações, além de possuir ação antioxidante.",
        receita: "Adicione 1 colher de sopa de casca de unha de gato picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, doenças autoimunes ou antes de cirurgias. Consulte um médico antes de usar.",
        indicacao: ["Sistema Imunológico"],
        dicasMedicas: "A unha de gato pode fortalecer o sistema imunológico, mas o acompanhamento médico é essencial para a prevenção e o tratamento de doenças.",
        nome: "Sistema Imunológico",
        funcao: "Proteção contra doenças e infecções.",
        componentes: ["Glóbulos brancos", "Linfócitos", "Macrófagos", "Timo", "Baço"]
      },
      {
        id: 35,
        nomeComumDaPlanta: "Cúrcuma",
        nomeCientifico: "Curcuma longa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Curcuma_longa_roots.jpg/656px-Curcuma_longa_roots.jpg",
        dadosMedicinais: "A cúrcuma, ou açafrão-da-terra, possui propriedades anti-inflamatórias e antioxidantes, auxiliando no fortalecimento do sistema imunológico e na prevenção de doenças. A curcumina, seu principal componente ativo, também possui ação antimicrobiana.",
        receita: "Adicione 1 colher de chá de cúrcuma em pó em 1 xícara de leite quente ou água. Misture bem e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de problemas de coagulação sanguínea ou antes de cirurgias. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Sistema Imunológico"],
        dicasMedicas: "A cúrcuma pode ser uma aliada na saúde do sistema imunológico, mas não substitui o acompanhamento médico e o tratamento adequado.",
        nome: "Sistema Imunológico",
        funcao: "Proteção contra doenças e infecções.",
        componentes: ["Glóbulos brancos", "Linfócitos", "Macrófagos", "Timo", "Baço"]
      },
      {
        id: 36,
        nomeComumDaPlanta: "Unha de gato",
        nomeCientifico: "Uncaria tomentosa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Uncaria_tomentosa.png/420px-Uncaria_tomentosa.png",
        dadosMedicinais: "A unha de gato possui propriedades anti-inflamatórias e antioxidantes, auxiliando no alívio de dores articulares e inflamações. Também pode fortalecer o sistema imunológico, importante para a saúde óssea.",
        receita: "Adicione 1 colher de sopa de casca de unha de gato picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, doenças autoimunes ou antes de cirurgias. Consulte um médico antes de usar.",
        indicacao: ["Articulações", "Ossos"],
        dicasMedicas: "A unha de gato pode auxiliar no alívio de dores articulares, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema esquelético.",
        nome: "Sistema Esquelético",
        funcao: "Suporte, estrutura e proteção.",
        componentes: ["Ossos", "Cartilagens", "Articulações"]
      },
      {
        id: 37,
        nomeComumDaPlanta: "Cúrcuma",
        nomeCientifico: "Curcuma longa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Curcuma_longa_roots.jpg/656px-Curcuma_longa_roots.jpg",
        dadosMedicinais: "A cúrcuma possui propriedades anti-inflamatórias e antioxidantes, auxiliando no alívio de dores articulares e inflamações. A curcumina, seu principal componente ativo, também pode contribuir para a saúde óssea.",
        receita: "Adicione 1 colher de chá de cúrcuma em pó em 1 xícara de leite quente ou água. Misture bem e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de problemas de coagulação sanguínea ou antes de cirurgias. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Articulações", "Ossos"],
        dicasMedicas: "A cúrcuma pode ser uma aliada na saúde do sistema esquelético, mas não substitui o acompanhamento médico e o tratamento adequado.",
        nome: "Sistema Esquelético",
        funcao: "Suporte, estrutura e proteção.",
        componentes: ["Ossos", "Cartilagens", "Articulações"]
      },
      {
        id: 38,
        nomeComumDaPlanta: "Cavalinha",
        nomeCientifico: "Equisetum arvense",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Equisetum_arvense_foliage.jpg/420px-Equisetum_arvense_foliage.jpg",
        dadosMedicinais: "A cavalinha é rica em silício, um mineral importante para a formação e manutenção dos ossos e cartilagens. Também possui ação anti-inflamatória e remineralizante.",
        receita: "Adicione 1 colher de sopa de cavalinha seca em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 xícaras por dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou problemas renais. Consulte um médico antes de usar.",
        indicacao: ["Ossos", "Cartilagens"],
        dicasMedicas: "A cavalinha pode auxiliar na saúde óssea e das cartilagens, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema esquelético.",
        nome: "Sistema Esquelético",
        funcao: "Suporte, estrutura e proteção.",
        componentes: ["Ossos", "Cartilagens", "Articulações"]
      },
      {
        id: 39,
        nomeComumDaPlanta: "Garra do diabo",
        nomeCientifico: "Harpagophytum procumbens",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Harpagophytum_5.jpg/420px-Harpagophytum_5.jpg",
        dadosMedicinais: "A garra do diabo possui propriedades anti-inflamatórias e analgésicas, auxiliando no alívio de dores articulares e musculares. É tradicionalmente usada para tratar artrite, artrose e outras condições inflamatórias.",
        receita: "Adicione 1 colher de chá de raiz de garra do diabo em pó em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, úlceras estomacais ou problemas cardíacos. Consulte um médico antes de usar.",
        indicacao: ["Articulações"],
        dicasMedicas: "A garra do diabo pode auxiliar no alívio de dores articulares, mas o acompanhamento médico é essencial para o diagnóstico e tratamento adequados de qualquer problema no sistema esquelético.",
        nome: "Sistema Esquelético",
        funcao: "Suporte, estrutura e proteção.",
        componentes: ["Ossos", "Cartilagens", "Articulações"]
      },
      {
        id: 40,
        nomeComumDaPlanta: "Boswellia",
        nomeCientifico: "Boswellia serrata",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Boswellia_serrata_%28Salai%29_in_Kinnarsani_WS%2C_AP_W2_IMG_5840.jpg/220px-Boswellia_serrata_%28Salai%29_in_Kinnarsani_WS%2C_AP_W2_IMG_5840.jpg",
        dadosMedicinais: "A boswellia possui propriedades anti-inflamatórias, auxiliando no alívio de dores articulares e inflamações. Seus compostos ativos podem ajudar a reduzir a degradação da cartilagem e a melhorar a mobilidade.",
        receita: "Adicione 1 colher de chá de resina de boswellia em pó em 1 xícara de leite quente ou água. Misture bem e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Articulações"],
        dicasMedicas: "A boswellia pode ser um auxiliar no alívio de dores articulares, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema esquelético.",
        nome: "Sistema Esquelético",
        funcao: "Suporte, estrutura e proteção.",
        componentes: ["Ossos", "Cartilagens", "Articulações"]
      },
      {
        id: 41,
        nomeComumDaPlanta: "Arnica",
        nomeCientifico: "Arnica montana",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Arnica_montana_%28flower_head%29.jpg/420px-Arnica_montana_%28flower_head%29.jpg",
        dadosMedicinais: "A arnica é conhecida por suas propriedades anti-inflamatórias e analgésicas, auxiliando no alívio de dores musculares, contusões e hematomas. Seu uso tópico é mais comum, mas o chá também pode ser utilizado com cautela.",
        receita: "Adicione 1 colher de chá de flores de arnica secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, feridas abertas ou hipersensibilidade à planta. O uso interno deve ser feito com orientação médica, pois a arnica pode ser tóxica em grandes quantidades.",
        indicacao: ["Músculos esqueléticos"],
        dicasMedicas: "A arnica pode auxiliar no alívio de dores musculares, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema muscular. O uso interno da arnica deve ser feito com cautela e orientação médica.",
        nome: "Sistema Muscular",
        funcao: "Movimento, postura e produção de calor.",
        componentes: ["Músculos esqueléticos", "Músculos lisos", "Músculo cardíaco"]
      },
      {
        id: 42,
        nomeComumDaPlanta: "Catuaba",
        nomeCientifico: "Trichilia catigua",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Trichilia_affinis_Govindoo.jpg/420px-Trichilia_affinis_Govindoo.jpg",
        dadosMedicinais: "A catuaba é tradicionalmente usada como estimulante e tônico, auxiliando no combate à fadiga física e mental. Pode melhorar a circulação sanguínea, o que beneficia a recuperação muscular.",
        receita: "Adicione 1 colher de sopa de casca de catuaba picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, hipertensão ou problemas cardíacos. Consulte um médico antes de usar.",
        indicacao: ["Músculos esqueléticos"],
        dicasMedicas: "A catuaba pode auxiliar no combate à fadiga e na recuperação muscular, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema muscular.",
        nome: "Sistema Muscular",
        funcao: "Movimento, postura e produção de calor.",
        componentes: ["Músculos esqueléticos", "Músculos lisos", "Músculo cardíaco"]
      },
      {
        id: 43,
        nomeComumDaPlanta: "Erva-mate",
        nomeCientifico: "Ilex paraguariensis",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/2/28/Ilex_paraguariensis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-074.jpg",
        dadosMedicinais: "A erva-mate contém cafeína e outros compostos estimulantes, que podem auxiliar no combate à fadiga e melhorar o desempenho físico. Também possui ação antioxidante e anti-inflamatória.",
        receita: "Adicione 1 colher de sopa de erva-mate em 1 xícara de água quente (não fervente). Abafe por 5 minutos, coe e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de hipertensão, insônia ou sensibilidade à cafeína. Consulte um médico antes de usar.",
        indicacao: ["Músculos esqueléticos"],
        dicasMedicas: "A erva-mate pode auxiliar no combate à fadiga e melhorar o desempenho físico, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema muscular.",
        nome: "Sistema Muscular",
        funcao: "Movimento, postura e produção de calor.",
        componentes: ["Músculos esqueléticos", "Músculos lisos", "Músculo cardíaco"]
      },
      {
        id: 44,
        nomeComumDaPlanta: "Canela",
        nomeCientifico: "Cinnamomum verum",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cinnamomum_verum_spices.jpg/380px-Cinnamomum_verum_spices.jpg",
        dadosMedicinais: "A canela possui propriedades anti-inflamatórias e antioxidantes, que podem auxiliar no alívio de dores musculares e inflamações. Também pode melhorar a circulação sanguínea, o que beneficia a recuperação muscular.",
        receita: "Adicione 1 pau de canela em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de gravidez ou lactação. Consulte um médico antes de usar.",
        indicacao: ["Músculos esqueléticos"],
        dicasMedicas: "A canela pode ser uma aliada no alívio de dores musculares, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema muscular.",
        nome: "Sistema Muscular",
        funcao: "Movimento, postura e produção de calor.",
        componentes: ["Músculos esqueléticos", "Músculos lisos", "Músculo cardíaco"]
      },
      {
        id: 45,
        nomeComumDaPlanta: "Guaraná",
        nomeCientifico: "Paullinia cupana",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Guaran%C3%A1_06.jpg/380px-Guaran%C3%A1_06.jpg",
        dadosMedicinais: "O guaraná é conhecido por suas propriedades estimulantes, devido à presença de cafeína. Pode auxiliar no combate à fadiga física e mental, melhorando o desempenho e a resistência muscular.",
        receita: "Adicione 1 colher de chá de guaraná em pó em 1 xícara de água fria ou suco de sua preferência. Misture bem e beba 1 vez ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de hipertensão, insônia ou sensibilidade à cafeína. Consulte um médico antes de usar.",
        indicacao: ["Músculos esqueléticos"],
        dicasMedicas: "O guaraná pode auxiliar no combate à fadiga e melhorar o desempenho físico, mas o acompanhamento médico é fundamental para o diagnóstico e tratamento adequados de qualquer problema no sistema muscular.",
        nome: "Sistema Muscular",
        funcao: "Movimento, postura e produção de calor.",
        componentes: ["Músculos esqueléticos", "Músculos lisos", "Músculo cardíaco"]
      },
      {
        id: 46,
        nomeComumDaPlanta: "Aloe vera",
        nomeCientifico: "Aloe barbadensis miller",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Aloe_Vera.jpg/330px-Aloe_Vera.jpg",
        dadosMedicinais: "A Aloe vera é conhecida por suas propriedades hidratantes, cicatrizantes e anti-inflamatórias, auxiliando no tratamento de queimaduras, feridas, irritações e inflamações da pele. Seu gel possui ação calmante e refrescante.",
        receita: "Aplique o gel fresco da folha de Aloe vera diretamente na área afetada, 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de alergia à planta. Em caso de irritação, suspenda o uso e procure um médico.",
        indicacao: ["Pele"],
        dicasMedicas: "A Aloe vera é um excelente aliado para a saúde da pele, mas lembre-se de que o acompanhamento médico é fundamental para o tratamento de qualquer condição dermatológica.",
        nome: "Sistema Tegumentar",
        funcao: "Proteção, regulação de temperatura e tato.",
        componentes: ["Pele", "Pelos", "Unhas", "Glândulas sudoríparas"]
    },
    {
        id: 47,
        nomeComumDaPlanta: "Calêndula",
        nomeCientifico: "Calendula officinalis",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Calendula_January_2008-1_filtered.jpg/420px-Calendula_January_2008-1_filtered.jpg",
        dadosMedicinais: "A calêndula possui propriedades anti-inflamatórias, cicatrizantes e antissépticas, auxiliando no tratamento de feridas, queimaduras, dermatites e irritações da pele. Suas flores possuem ação calmante e regeneradora.",
        receita: "Prepare um chá com 1 colher de sopa de flores de calêndula secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e aplique compressas mornas na área afetada, 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de alergia à planta. Em caso de irritação, suspenda o uso e procure um médico.",
        indicacao: ["Pele"],
        dicasMedicas: "A calêndula é uma ótima opção para o cuidado da pele, mas lembre-se de que o acompanhamento médico é essencial para o tratamento de qualquer condição dermatológica.",
        nome: "Sistema Tegumentar",
        funcao: "Proteção, regulação de temperatura e tato.",
        componentes: ["Pele", "Pelos", "Unhas", "Glândulas sudoríparas"]
    },
    {
        id: 48,
        nomeComumDaPlanta: "Camomila",
        nomeCientifico: "Matricaria chamomilla",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Matricaria_February_2008-1.jpg/420px-Matricaria_February_2008-1.jpg",
        dadosMedicinais: "A camomila possui propriedades calmantes, anti-inflamatórias e antialérgicas, auxiliando no tratamento de irritações, alergias e inflamações da pele. Seu chá também pode ser usado para acalmar e promover o bem-estar.",
        receita: "Prepare um chá com 1 colher de sopa de flores de camomila secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e aplique compressas mornas na área afetada ou beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de alergia à planta. Em caso de irritação, suspenda o uso e procure um médico.",
        indicacao: ["Pele"],
        dicasMedicas: "A camomila é uma excelente opção para o cuidado da pele, mas lembre-se de que o acompanhamento médico é essencial para o tratamento de qualquer condição dermatológica.",
        nome: "Sistema Tegumentar",
        funcao: "Proteção, regulação de temperatura e tato.",
        componentes: ["Pele", "Pelos", "Unhas", "Glândulas sudoríparas"]
    },
    {
        id: 49,
        nomeComumDaPlanta: "Bardana",
        nomeCientifico: "Arctium lappa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/ArctiumLappa1.jpg/420px-ArctiumLappa1.jpg",
        dadosMedicinais: "A bardana possui propriedades depurativas e anti-inflamatórias, auxiliando no tratamento de problemas de pele como acne, eczema e psoríase. Suas raízes e folhas podem ser utilizadas em chás ou compressas.",
        receita: "Prepare um chá com 1 colher de sopa de raiz de bardana picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia. Para uso tópico, aplique compressas mornas do chá na área afetada.",
        contraIndicacoes: "Evite o uso em caso de alergia à planta. Em caso de irritação, suspenda o uso e procure um médico.",
        indicacao: ["Pele"],
        dicasMedicas: "A bardana pode ser uma aliada no tratamento de problemas de pele, mas lembre-se de que o acompanhamento médico é essencial para o diagnóstico e tratamento adequados de qualquer condição dermatológica.",
        nome: "Sistema Tegumentar",
        funcao: "Proteção, regulação de temperatura e tato.",
        componentes: ["Pele", "Pelos", "Unhas", "Glândulas sudoríparas"]
    },
    {
        id: 50,
        nomeComumDaPlanta: "Hamamélis",
        nomeCientifico: "Hamamelis virginiana",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Hamamelis_virginiana_FlowersLeaves_BotGardBln0906.JPG/675px-Hamamelis_virginiana_FlowersLeaves_BotGardBln0906.JPG",
        dadosMedicinais: "A hamamélis possui propriedades adstringentes e anti-inflamatórias, auxiliando no tratamento de acne, irritações, inflamações e hemorroidas. Sua casca e folhas podem ser utilizadas em chás ou compressas.",
        receita: "Prepare um chá com 1 colher de sopa de folhas de hamamélis secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e aplique compressas mornas na área afetada, 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de alergia à planta. Em caso de irritação, suspenda o uso e procure um médico.",
        indicacao: ["Pele"],
        dicasMedicas: "A hamamélis é uma ótima opção para o cuidado da pele, mas lembre-se de que o acompanhamento médico é essencial para o tratamento de qualquer condição dermatológica.",
        nome: "Sistema Tegumentar",
        funcao: "Proteção, regulação de temperatura e tato.",
        componentes: ["Pele", "Pelos", "Unhas", "Glândulas sudoríparas"]
    },
    {
        id: 51,
        nomeComumDaPlanta: "Tribulus terrestris",
        nomeCientifico: "Tribulus terrestris",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Tribulus_terrestris_%28Family_Zygophyllaceae%29.jpg/375px-Tribulus_terrestris_%28Family_Zygophyllaceae%29.jpg",
        dadosMedicinais: "O Tribulus terrestris é conhecido por suas propriedades estimulantes da libido e da produção de testosterona, auxiliando na melhora da função sexual masculina e feminina. Também pode ajudar a aumentar a fertilidade e a massa muscular.",
        receita: "Adicione 1 colher de chá de Tribulus terrestris em pó em 1 xícara de água ou suco de sua preferência. Misture bem e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, hipertensão ou problemas cardíacos. Consulte um médico antes de usar.",
        indicacao: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"],
        dicasMedicas: "O Tribulus terrestris pode ser um aliado na saúde sexual, mas lembre-se de que o acompanhamento médico é fundamental para o tratamento de qualquer condição relacionada à fertilidade ou à função sexual.",
        nome: "Sistema Reprodutor",
        funcao: "Reprodução humana.",
        componentes: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"]
    },
    {
        id: 52,
        nomeComumDaPlanta: "Maca peruana",
        nomeCientifico: "Lepidium meyenii",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Lepidium_meyenii%2C_Tsaghkadzor%2C_in_culture.jpg/420px-Lepidium_meyenii%2C_Tsaghkadzor%2C_in_culture.jpg",
        dadosMedicinais: "A maca peruana é conhecida por suas propriedades energéticas e estimulantes da libido, auxiliando na melhora da função sexual masculina e feminina. Também pode ajudar a equilibrar os hormônios e a aumentar a fertilidade.",
        receita: "Adicione 1 colher de sopa de maca peruana em pó em vitaminas, iogurtes ou sucos. Consuma 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou problemas de tireoide. Consulte um médico antes de usar.",
        indicacao: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"],
        dicasMedicas: "A maca peruana pode ser uma aliada na saúde sexual e hormonal, mas lembre-se de que o acompanhamento médico é fundamental para o tratamento de qualquer condição relacionada à fertilidade ou à função sexual.",
        nome: "Sistema Reprodutor",
        funcao: "Reprodução humana.",
        componentes: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"]
    },
    {
        id: 53,
        nomeComumDaPlanta: "Damiana",
        nomeCientifico: "Turnera diffusa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Tunera_diffusa_2.jpg/375px-Tunera_diffusa_2.jpg",
        dadosMedicinais: "A damiana é tradicionalmente usada como afrodisíaco e estimulante da libido, auxiliando na melhora da função sexual masculina e feminina. Também pode ajudar a aliviar sintomas da menopausa e a reduzir a ansiedade.",
        receita: "Adicione 1 colher de sopa de folhas de damiana secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou diabetes. Consulte um médico antes de usar.",
        indicacao: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"],
        dicasMedicas: "A damiana pode ser uma aliada na saúde sexual, mas lembre-se de que o acompanhamento médico é fundamental para o tratamento de qualquer condição relacionada à fertilidade ou à função sexual.",
        nome: "Sistema Reprodutor",
        funcao: "Reprodução humana.",
        componentes: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"]
    },
    {
        id: 54,
        nomeComumDaPlanta: "Ginseng",
        nomeCientifico: "Panax ginseng",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Ginsengpflanze.jpg/420px-Ginsengpflanze.jpg",
        dadosMedicinais: "O ginseng é conhecido por suas propriedades adaptogênicas e estimulantes, auxiliando no combate ao estresse e na melhora da energia e da vitalidade. Também pode ajudar a melhorar a função sexual masculina e feminina.",
        receita: "Adicione 1 colher de chá de raiz de ginseng em pó em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 1 vez ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, hipertensão ou problemas cardíacos. Consulte um médico antes de usar.",
        indicacao: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"],
        dicasMedicas: "O ginseng pode ser um aliado na saúde sexual e no combate ao estresse, mas lembre-se de que o acompanhamento médico é fundamental para o tratamento de qualquer condição relacionada à fertilidade ou à função sexual.",
        nome: "Sistema Reprodutor",
        funcao: "Reprodução humana.",
        componentes: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"]
    },
    {
        id: 55,
        nomeComumDaPlanta: "Chá de framboesa",
        nomeCientifico: "Rubus idaeus",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Framboos_vruchten.jpg/225px-Framboos_vruchten.jpg",
        dadosMedicinais: "O chá de framboesa é tradicionalmente usado para fortalecer o útero e preparar o corpo para o parto. Pode ajudar a aliviar cólicas menstruais e regular o ciclo menstrual.",
        receita: "Adicione 1 colher de sopa de folhas de framboesa secas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, especialmente nos primeiros meses, ou se tiver histórico de parto prematuro. Consulte um médico antes de usar.",
        indicacao: ["Órgãos sexuais femininos"],
        dicasMedicas: "O chá de framboesa pode ser um aliado na saúde feminina, mas lembre-se de que o acompanhamento médico é fundamental durante a gravidez e para o tratamento de qualquer condição relacionada ao sistema reprodutor.",
        nome: "Sistema Reprodutor",
        funcao: "Reprodução humana.",
        componentes: ["Órgãos sexuais masculinos", "Órgãos sexuais femininos"]
    },
    {
        id: 56,
        nomeComumDaPlanta: "Echinacea",
        nomeCientifico: "Echinacea purpurea",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/EchinaceaPurpureaMaxima1a.UME.JPG/375px-EchinaceaPurpureaMaxima1a.UME.JPG",
        dadosMedicinais: "A equinácea é conhecida por suas propriedades estimulantes do sistema imunológico, o que indiretamente beneficia o sistema linfático, auxiliando na defesa do organismo e na drenagem de líquidos. Possui ação anti-inflamatória e antioxidante.",
        receita: "Adicione 1 colher de sopa de raiz de equinácea picada em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba até 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de doenças autoimunes ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Sistema Linfático"],
        dicasMedicas: "A equinácea pode auxiliar na saúde do sistema linfático, mas o acompanhamento médico é essencial para o tratamento de qualquer condição relacionada ao sistema linfático ou imunológico.",
        nome: "Sistema Linfático",
        funcao: "Drenagem de líquidos, transporte de células de defesa e absorção de gorduras.",
        componentes: ["Vasos linfáticos", "Linfonodos", "Timo", "Baço"]
    },
    {
        id: 57,
        nomeComumDaPlanta: "Centella asiática",
        nomeCientifico: "Centella asiatica",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Starr_020803-0094_Centella_asiatica.jpg/375px-Starr_020803-0094_Centella_asiatica.jpg",
        dadosMedicinais: "A centella asiática possui propriedades anti-inflamatórias e cicatrizantes, auxiliando na redução de edemas e no tratamento de problemas circulatórios e linfáticos. Também melhora a circulação sanguínea e fortalece os vasos.",
        receita: "Adicione 1 colher de sopa de folhas de centella asiática picadas em 1 xícara de água fervente. Abafe por 10 minutos, coe e beba 2 a 3 vezes ao dia.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação ou hipersensibilidade à planta. Consulte um médico antes de usar.",
        indicacao: ["Vasos linfáticos"],
        dicasMedicas: "A centella asiática pode ser uma aliada na saúde do sistema linfático, mas o acompanhamento médico é essencial para o tratamento de qualquer condição relacionada à circulação ou ao sistema linfático.",
        nome: "Sistema Linfático",
        funcao: "Drenagem de líquidos, transporte de células de defesa e absorção de gorduras.",
        componentes: ["Vasos linfáticos", "Linfonodos", "Timo", "Baço"]
    },
    {
        id: 58,
        nomeComumDaPlanta: "Castanha-da-índia",
        nomeCientifico: "Aesculus hippocastanum",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Gebarsten_bolster_van_een_paardenkastanje_%28Aesculus%29_13-10-2022_%28d.j.b.%29_03.jpg/330px-Gebarsten_bolster_van_een_paardenkastanje_%28Aesculus%29_13-10-2022_%28d.j.b.%29_03.jpg",
        dadosMedicinais: "A castanha-da-índia contém aescina, um composto com propriedades anti-inflamatórias e vasoconstritoras, auxiliando na redução de edemas, varizes e outros problemas circulatórios e linfáticos. Fortalece as paredes dos vasos e melhora a circulação.",
        receita: "Utilize extrato de castanha-da-índia em cápsulas ou pomadas, seguindo as orientações do fabricante ou de um profissional de saúde.",
        contraIndicacoes: "Evite o uso em caso de gravidez, lactação, problemas hepáticos ou renais. Consulte um médico antes de usar.",
        indicacao: ["Vasos linfáticos"],
        dicasMedicas: "A castanha-da-índia pode ser benéfica para a saúde do sistema linfático e circulatório, mas o acompanhamento médico é fundamental para o tratamento de qualquer condição relacionada a esses sistemas.",
        nome: "Sistema Linfático",
        funcao: "Drenagem de líquidos, transporte de células de defesa e absorção de gorduras.",
        componentes: ["Vasos linfáticos", "Linfonodos", "Timo", "Baço"]
    },
    {
        id: 59,
        nomeComumDaPlanta: "Açafrão-da-terra",
        nomeCientifico: "Curcuma longa",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Turmericroot.jpg/363px-Turmericroot.jpg",
        dadosMedicinais: "O açafrão-da-terra possui propriedades anti-inflamatórias e antioxidantes, auxiliando na redução de inflamações e no fortalecimento do sistema imunológico, o que indiretamente beneficia o sistema linfático. A curcumina, seu principal componente ativo, também possui ação antimicrobiana.",
        receita: "Adicione 1 colher de chá de açafrão-da-terra em pó em 1 xícara de leite quente ou água. Misture bem e beba 1 a 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de problemas de coagulação sanguínea ou antes de cirurgias. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Sistema Linfático"],
        dicasMedicas: "O açafrão-da-terra pode ser um aliado na saúde do sistema linfático, mas o acompanhamento médico é essencial para o tratamento de qualquer condição relacionada ao sistema linfático ou imunológico.",
        nome: "Sistema Linfático",
        funcao: "Drenagem de líquidos, transporte de células de defesa e absorção de gorduras.",
        componentes: ["Vasos linfáticos", "Linfonodos", "Timo", "Baço"]
    },
    {
        id: 60,
        nomeComumDaPlanta: "Gengibre",
        nomeCientifico: "Zingiber officinale",
        imagemDaPlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Zingiber_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-146.jpg/420px-Zingiber_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-146.jpg",
        dadosMedicinais: "O gengibre possui propriedades anti-inflamatórias e antioxidantes, auxiliando na redução de inflamações e no fortalecimento do sistema imunológico, o que indiretamente beneficia o sistema linfático. Também melhora a circulação sanguínea.",
        receita: "Rale 1 pedaço de gengibre e adicione em 1 xícara de água fervente. Abafe por 5 minutos, coe e beba 2 vezes ao dia.",
        contraIndicacoes: "Evite o consumo excessivo em caso de problemas de coagulação sanguínea ou úlceras estomacais. Consulte um médico em caso de gravidez ou lactação.",
        indicacao: ["Sistema Linfático"],
        dicasMedicas: "O gengibre pode ser um aliado na saúde do sistema linfático, mas o acompanhamento médico é essencial para o tratamento de qualquer condição relacionada ao sistema linfático ou imunológico.",
        nome: "Sistema Linfático",
        funcao: "Drenagem de líquidos, transporte de células de defesa e absorção de gorduras.",
        componentes: ["Vasos linfáticos", "Linfonodos", "Timo", "Baço"]
    }

]